--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NuthMC/ReportSystem
build-by-default: true
branches:
- main
- pm4
projects:
  ReportSystem:
    path: ""
    logo: icon.png
    
---
